# Site settings
locale: "en-GB"
title: downthewire.co.uk
email: website@downthewire.co.uk
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
twitter_username: th0mpsy
github_username: thompsy
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Andrew Thompson"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Edinburgh based software engineer, bookworm and Jesus follower."
  location: "Edinburgh, UK"
  email: "website@downthewire.co.uk"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://downthewire.co.uk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/th0mpsy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thompsy"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/th0mpsy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thompsy"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
